AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: ALB Log Pipe - Process Application Load Balancer access logs

Globals:
  Function:
    Environment:
      Variables:
        AWS_ENDPOINT: "http://localstack:4566"
        AWS_REGION: "eu-west-1"
        AWS_ACCESS_KEY_ID: "test"
        AWS_SECRET_ACCESS_KEY: "test"

Parameters:
  BucketPrefix:
    Type: String
    Description: Prefix for the S3 bucket name
    Default: "my-alb-logs"
  ElbAccountId:
    Type: String
    Description: ELB Account ID for the region (see https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html#attach-bucket-policy)

Resources:
  ProcessLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: .
      Timeout: 60
      MemorySize: 128
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource:
                !Sub "arn:aws:s3:::${BucketPrefix}-${AWS::AccountId}/*"
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:DeleteLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*"
      Environment:
        Variables:
          TARGETS: "cloudwatch"
          CLOUDWATCH_LOG_GROUP: "alb-log-pipe/my-log-group"
          CLOUDWATCH_LOG_STREAM: "my-log-stream"

  LogBucket:
    Type: AWS::S3::Bucket
    DependsOn: ProcessLogFunction
    Properties:
      BucketName: !Sub "${BucketPrefix}-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: !Sub "${BucketPrefix}-lifecycle"
            Status: Enabled
            ExpirationInDays: 7
            Prefix: "AWSLogs/"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ProcessLogFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "AWSLogs/"

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${ElbAccountId}:root"
            Action: s3:PutObject
            Resource:
              !Sub "arn:aws:s3:::${BucketPrefix}-${AWS::AccountId}/*"

Outputs:
  LogBucketName:
    Description: "Name of S3 bucket - use this when configuring ALB access logs"
    Value: !Ref LogBucket
